FROM mhart/alpine-node:latest as react-build
WORKDIR /usr/app/react
COPY ["package.json", "./"]
RUN npm install
COPY . .
RUN npm run build

FROM nginx
COPY --from=react-build /usr/app/react/build /usr/share/nginx/html